import type { Metadata } from "next";
import "./globals.css";
import { Benefits } from "../components/benefits";
import  About  from '../components/About'
import Slider from '../components/Slider'
import Accordian from '../components/Accordian'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="">
          <Slider/>
          <Accordian/>
        {children}
      </body>
    </html>
  );
}
