import type { Metadata } from "next";
import "./globals.css";
import Benefits from "../components/benefits";
import About from '../components/About'
import Slider from '../components/Testimonials'
import Accordian from '../components/Accordian'
import Placements from '../components/Placements'
import CareerSupport from '../components/CareerSupport'
import Mentors from '../components/Mentors'
import Certificate from "../components/Certificate";
import Testimonials from "../components/Testimonials";
import  Languages  from "../components/languages&tool";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="">
     <Benefits/>
        <Languages/>

        {children}
      </body>
    </html>
  );
}
